GET http://localhost:3000/ads
###
GET http://localhost:3000/ads?id=9
###
GET http://localhost:3000/ads?categorie=autre
###
GET http://localhost:3000/ads?tag=bleu
###
GET http://localhost:3000/ads?title=pierre
###
GET http://localhost:3000/ads/5
###
POST http://localhost:3000/ads
Content-Type: application/json

{
    "title": "Renault clio II",
    "description":
      "Best car ever!",
    "owner": "car.seller@gmail.com",
    "price": 10000,
    "picture":
      "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Paris",
    "createdAt": "2023-10-05T10:14:15.922Z",
    "categorie": 1,
    "tags" : [{"id":1}, {"id":2}, {"id" : 3}]
}

###

DELETE http://localhost:3000/ads/2

###

PUT http://localhost:3000/ads/9
Content-Type: application/json

{
    "categorie" : 1
}