GET http://localhost:3000/categorie
###
GET http://localhost:3000/categorie?name=voiture
###
POST http://localhost:3000/categorie
Content-Type: application/json

{
    "name" : "jouer"
}

###
DELETE http://localhost:3000/categorie/4
###
PUT http://localhost:3000/categorie/4
Content-Type: application/json

{
    "name" : "jeux"
}